[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"


[project]
name = "pr-aide"
version = "0.1.0"
description = "High-performance async Python API skeleton with Redis caching and CI"
authors = [ { name = "Huzefa Batth" } ]
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
"fastapi>=0.115",
"uvicorn[standard]>=0.30",
"redis>=5.0",
"pydantic>=2.7",
"pydantic-settings>=2.2"
]


[project.optional-dependencies]
dev = [
"pytest>=8.0",
"pytest-asyncio>=0.23",
"httpx>=0.27",
"black>=24.3",
"isort>=5.13",
"mypy>=1.10",
"ruff>=0.6",
"types-redis"
]


[tool.black]
line-length = 100


[tool.isort]
profile = "black"
line_length = 100


[tool.ruff]
line-length = 100
select = ["E", "F", "I"]


[tool.pytest.ini_options]
addopts = "-q"
pythonpath = ["."]